server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/photorizedb?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul"
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET_NAME}
      base-url: https://%s.s3.%s.amazonaws.com/%s

logging:
  level:
    root: INFO
    com:
      shutter:
        photorize: DEBUG