server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET_NAME}
      base-url: https://%s.s3.%s.amazonaws.com/%s
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jwt:
    secret: ${JWT_SECRET}
    expire:
      time:
        access: ${JWT_ACCESS_TIME}
        refresh: ${JWT_REFRESH_TIME}


logging:
  level:
    root: INFO
    com:
      shutter:
        photorize: DEBUG